apiVersion: skaffold/v3
kind: Config
metadata:
  name: myapp
build:
  artifacts:
    - image: us-central1-docker.pkg.dev/platform-tyrconsulting/applications/tyr-java-service
      docker:
        dockerfile: Dockerfile

profiles:
  - name: dev
  - name: qa
  - name: prod