# cloudbuild.yaml
steps:
  # Gradle build & test
  - name: 'gradle:8-jdk17'
    entrypoint: gradle
    env: 
      - 'GRADLE_USER_HOME=/workspace/.gradle'
    args:
      - '--no-daemon'
      - '--parallel'
      - '--console=plain'
      - '--info'
      - '-PmavenRepoUrl=https://maven-central.storage-download.googleapis.com/maven2/'
      - 'build'      
    id: 'build-and-test-app'

   # Docker build
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:latest',
      '--build-arg', 'JAR_FILE=build/libs/*.jar',
      '--cache-from', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:latest',
      '.'
    ]
    id: 'build-container-image'
    waitFor:
    - build-and-test-app

  # Create Cloud Deploy release
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        GITHUB_PAT=$(gcloud secrets versions access latest --secret="${_GITHUB_SECRET}") && \
        git clone https:///$$GITHUB_PAT@${_PLATFORM_REPO} && \
        gcloud deploy releases create release-${SHORT_SHA} \
        --delivery-pipeline=${_SERVICE_NAME}-pipeline \
        --region=${_REGION} \
        --annotations=commit_sha=${REVISION_ID},build_id=$BUILD_ID \
        --labels=env=dev \
        --source=tyr-platform/apps/${_SERVICE_NAME}/ \
        --images=${_SERVICE_NAME}=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}
    id: 'create-deploy-release'
    waitFor:
    - build-container-image

# Build timeout
timeout: '600s'  

# Specify the images to push
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:latest'

substitutions:
  _REGION: 'us-central1'  
  _SERVICE_NAME: 'tyr-java-service'
  _REPOSITORY: 'applications'
  _PLATFORM_REPO: 'github.com/pbrumblay/tyr-platform.git'
  _GITHUB_SECRET: 'github-pat'

# Configure artifact caching for Gradle
options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true